[build]
  command = "concurrently \"cd back && node server.js\" \"cd front && npm run build && serve -s build\""
  publish = "build"
[dev]
  command = "concurrently \"cd back && node server.js\" \"cd front && npm start\""
